version: "3.8"

networks:
  loki:
    driver: bridge

services:
  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - loki

  grafana:
    image: grafana/grafana:9.1.7  
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3200:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - loki
